default_platform(:android)

        platform :android do

            # LANE 1
            desc "Build the AAB file"
            lane :build do
            # Generate AAB file
            gradle(
                task: "bundle",
                build_type: "Release"
            )
            end

            # LANE 1
            desc "Publish a new version to the Google Play (INTERNAL)"
            lane :internal do |options|

                build
                # Retrieve the version code from the gradle file
                version_code = options[:version_code]
                
                
                # Upload the AAB to play store (internal track)
                upload_to_play_store(
                track: 'internal',
                validate_only: false,
                version_code: version_code, 
                aab: "../build/app/outputs/bundle/release/app-release.aab",
                skip_upload_screenshots: true 
                )

                
            end

            # LANE 2
            desc "Publish a new version to the Google Play (PROD)"
            lane :production do

                # Generate AAB file
                gradle(
                task: "bundle",
                build_type: "Release"
                )

                # Upload the AAB to play store (production track)
                upload_to_play_store(track: 'production')
            end
        end
        # Custom method to extract version code from build.gradle
        def get_version_code
            build_gradle = File.read("android/app/build.gradle")
            version_code_line = build_gradle.match(/versionCode\s+(\d+)/)
            version_code = version_code_line[1].to_i if version_code_line
            version_code
        end